/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorTreatmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    // private Network network;

    /**
     * Creates new form DoctortWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.doctorOrganization = organization;
        // this.network = network;

        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest docrequest : doctorOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            // row[0] = request.getDate();
            //row[0] = request;
            row[0] = docrequest;
            row[1] = docrequest.getDate();
            row[2] = docrequest.getMessage();
            //row[2] = docrequest.getSender().getEmployee().getName();
            row[3] = docrequest.getReceiver() == null ? null : docrequest.getReceiver().getEmployee().getName();
            row[4] = docrequest.getStatus();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lasttimeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sextextfield1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addressline2textfield1 = new javax.swing.JTextField();
        middlenametextfield1 = new javax.swing.JTextField();
        lastnametextfield1 = new javax.swing.JTextField();
        agetextfield1 = new javax.swing.JTextField();
        addressline1textfield1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        citytexxtfield1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        statetextfield1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        firstnametextfield1 = new javax.swing.JTextField();
        dobtextfield1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        countrytextfield1 = new javax.swing.JTextField();
        phonenotextfield1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        occupationTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        commentsTextFiled = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultJTextField1 = new javax.swing.JTextField();
        freemedicineTextField1 = new javax.swing.JTextField();
        QuantityTextfield1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nextTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Disease/Symptoms", "Date", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workRequestJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 510, 96));

        assignJButton.setBackground(new java.awt.Color(0, 102, 102));
        assignJButton.setForeground(new java.awt.Color(255, 255, 255));
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        processJButton.setBackground(new java.awt.Color(0, 102, 102));
        processJButton.setForeground(new java.awt.Color(255, 255, 255));
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        refreshJButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("WELCOME TO DOCTOR WORKAREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        lasttimeTextField.setEditable(false);
        lasttimeTextField.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(lasttimeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 270, 20));

        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel4.setText("ADDRESS LINE 2:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        sextextfield1.setEditable(false);
        sextextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(sextextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 270, 20));

        jLabel16.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel16.setText("MIDDLE NAME: ");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel17.setText("MARITAL STATUS: ");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel18.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel18.setText("LAST NAME:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel19.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel19.setText("AGE:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 140, -1));

        jLabel20.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel20.setText("SEX: ");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 140, -1));

        jLabel21.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel21.setText("FIRST NAME: ");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        addressline2textfield1.setEditable(false);
        addressline2textfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(addressline2textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 270, 20));

        middlenametextfield1.setEditable(false);
        middlenametextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(middlenametextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 290, 20));

        lastnametextfield1.setEditable(false);
        lastnametextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(lastnametextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 290, 20));

        agetextfield1.setEditable(false);
        agetextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(agetextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 270, 20));

        addressline1textfield1.setEditable(false);
        addressline1textfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(addressline1textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 290, 20));

        jLabel22.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel22.setText("ADDRESS LINE 1: ");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        citytexxtfield1.setEditable(false);
        citytexxtfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(citytexxtfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 290, 20));

        jLabel23.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel23.setText("PHONE NUMBER: ");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        statetextfield1.setEditable(false);
        statetextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(statetextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 270, 20));

        jLabel24.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel24.setText("STATE:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        firstnametextfield1.setEditable(false);
        firstnametextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(firstnametextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 290, 20));

        dobtextfield1.setEditable(false);
        dobtextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(dobtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 270, 20));

        jLabel26.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel26.setText("DATE OF BIRTH:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 200, -1));

        jLabel27.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("ENTER PERSONAL INFORMATION: ");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel28.setText("COUNTRY:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        countrytextfield1.setEditable(false);
        countrytextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(countrytextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 290, 20));

        phonenotextfield1.setEditable(false);
        phonenotextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(phonenotextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 270, 20));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Seperated");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Married");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Single");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Widowed");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, -1, -1));

        jLabel30.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel30.setText("OCCUPATION: ");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        occupationTextField1.setEditable(false);
        occupationTextField1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(occupationTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 290, 20));

        jLabel13.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel13.setText("CITY: ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("TREATMENT HISTORY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel3.setText("RESULT :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        commentsTextFiled.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(commentsTextFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 230, -1));

        jLabel5.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel5.setText("FREE MEDICINE : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel6.setText("OTHER COMMENTS :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel7.setText("QUANTITY: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        resultJTextField1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(resultJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 230, -1));

        freemedicineTextField1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(freemedicineTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 230, -1));

        QuantityTextfield1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(QuantityTextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 230, -1));

        jLabel8.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel8.setText("NEXT APPOINTMENT DATE:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        nextTextField1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(nextTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 230, -1));

        jLabel9.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("TREATMENT REQUEST: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel25.setText("WHEN WAS THE LAST TIME YOU HAD DISEASE SYMPTOM (If Yes please mention, else mention as No)?");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 590, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest docrequest = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

        docrequest.setReceiver(userAccount);
        docrequest.setStatus("Pending");
        populateTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {

            if (selectedRow < 0) {
                return;
            }

            DoctorTreatmentWorkRequest docrequest = (DoctorTreatmentWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

            docrequest.setStatus("Processing");

            ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, userAccount, docrequest, enterprise, business);
            userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        } else {
            JOptionPane.showMessageDialog(null, "Please Select any row");
        }

    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void workRequestJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workRequestJTableMouseClicked
        // TODO add your handling code here:

        int selectedrow = workRequestJTable.getSelectedRow();

        if (selectedrow >= 0) {

            DoctorTreatmentWorkRequest docrequest = (DoctorTreatmentWorkRequest) workRequestJTable.getValueAt(selectedrow, 0);
            firstnametextfield1.setText(docrequest.getFirstName());
            middlenametextfield1.setText(docrequest.getMiddleName());
            lastnametextfield1.setText(docrequest.getLastName());
            agetextfield1.setText(String.valueOf(docrequest.getAge()));
            sextextfield1.setText(docrequest.getSex());
            addressline1textfield1.setText(docrequest.getAddressLine1());
            addressline2textfield1.setText(docrequest.getAddressLine2());
            citytexxtfield1.setText(docrequest.getCity());
            statetextfield1.setText(docrequest.getState());
            countrytextfield1.setText(docrequest.getCountry());
            dobtextfield1.setText(docrequest.getDOB());
            phonenotextfield1.setText(String.valueOf(docrequest.getPhoneNo()));
            occupationTextField1.setText(docrequest.getOccupation());
            lasttimeTextField.setText(docrequest.getLastTimeDisease());

            resultJTextField1.setText(docrequest.getTestResult());
            freemedicineTextField1.setText(docrequest.getFreeMed());
            QuantityTextfield1.setText(String.valueOf(docrequest.getQuantity()));
            nextTextField1.setText(docrequest.getAppointmentDate());
            commentsTextFiled.setText(docrequest.getComments());

            if (docrequest.getMaritalStatus().equals(jRadioButton2.getText())) {
                jRadioButton2.setSelected(true);
            } else if (docrequest.getMaritalStatus().equals(jRadioButton3.getText())) {
                jRadioButton3.setSelected(true);
            } else if (docrequest.getMaritalStatus().equals(jRadioButton4.getText())) {
                jRadioButton4.setSelected(true);
            } else {
                jRadioButton1.setSelected(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select any row");
        }
    }//GEN-LAST:event_workRequestJTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantityTextfield1;
    private javax.swing.JTextField addressline1textfield1;
    private javax.swing.JTextField addressline2textfield1;
    private javax.swing.JTextField agetextfield1;
    private javax.swing.JButton assignJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField citytexxtfield1;
    private javax.swing.JTextField commentsTextFiled;
    private javax.swing.JTextField countrytextfield1;
    private javax.swing.JTextField dobtextfield1;
    private javax.swing.JTextField firstnametextfield1;
    private javax.swing.JTextField freemedicineTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnametextfield1;
    private javax.swing.JTextField lasttimeTextField;
    private javax.swing.JTextField middlenametextfield1;
    private javax.swing.JTextField nextTextField1;
    private javax.swing.JTextField occupationTextField1;
    private javax.swing.JTextField phonenotextfield1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField resultJTextField1;
    private javax.swing.JTextField sextextfield1;
    private javax.swing.JTextField statetextfield1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
