/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierInventory;

import Business.Organization.SupplierInventoryOrganization;
import Business.RawMaterial.RawMaterial;
import Business.RawMaterial.RawMaterialsDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AMY
 */
public class AddRawMaterialJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierInventoryOrganization supplierInventoryOrganization;

    /**
     * Creates new form AddRawMaterialJPanel
     */
    public AddRawMaterialJPanel(JPanel userProcessContainer, SupplierInventoryOrganization supplierInventoryOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierInventoryOrganization = supplierInventoryOrganization;
        populateComboBox();
    }

    public void populateComboBox() {
        cmbRawMaterial.removeAllItems();
        for (RawMaterial.RawMaterialType rawMaterial : RawMaterial.RawMaterialType.values()) {
            cmbRawMaterial.addItem(rawMaterial);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        qtyTextField = new javax.swing.JTextField();
        ADDButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbRawMaterial = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel1.setText("RAW MATERIAL NAME:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel2.setText("QUANTITY:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel3.setText("RAW MATERIAL TYPE :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        nameTextField.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 180, -1));

        qtyTextField.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(qtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 180, -1));

        ADDButton.setBackground(new java.awt.Color(0, 102, 102));
        ADDButton.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        ADDButton.setForeground(new java.awt.Color(255, 255, 255));
        ADDButton.setText("CLICK TO ADD");
        ADDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDButtonActionPerformed(evt);
            }
        });
        add(ADDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("WELCOME TO RAW MATERIAL WORKAREA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        cmbRawMaterial.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(cmbRawMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 190, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ADDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDButtonActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();
         boolean isNameValid = validateStrings(name);
        int qty;
            boolean isValid = true;
            try {
                qty = Integer.parseInt(qtyTextField.getText());
            } catch (NumberFormatException e) {
                isValid = false;
                JOptionPane.showMessageDialog(null, "Enter valid qty", "Error", JOptionPane.ERROR_MESSAGE);
                throw e;
            }
            if(qty <=0){
                isValid = false;
                JOptionPane.showMessageDialog(null, "Enter valid qty", "Error", JOptionPane.ERROR_MESSAGE);
            }
          if (isValid && isNameValid) {
            RawMaterial.RawMaterialType type = (RawMaterial.RawMaterialType) cmbRawMaterial.getSelectedItem();
            RawMaterialsDirectory rawMaterialDirectory = supplierInventoryOrganization.getRawMaterialsDirectory();
            RawMaterial rawMaterial = rawMaterialDirectory.addRawMaterial();
            rawMaterial.setName(name);
            rawMaterial.setQuantity(qty);
            rawMaterial.setRawMaterialType(type);
            JOptionPane.showMessageDialog(null, "Raw Material added");
        }
    }//GEN-LAST:event_ADDButtonActionPerformed
public boolean validateStrings(String name){
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter mandatory value", "Error", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        Pattern pattern = Pattern.compile("[a-zA-Z ]*");
        Matcher matcher = pattern.matcher(name);
         if (!matcher.matches()) {
             
            JOptionPane.showMessageDialog(null, "Please Enter valid string value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
      }
        return true;
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SupplierInventoryWorkAreaJPanel supplierInventoryWorkAreaJPanel = (SupplierInventoryWorkAreaJPanel) component;
        supplierInventoryWorkAreaJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox cmbRawMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField qtyTextField;
    // End of variables declaration//GEN-END:variables
}
