/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Transport;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MarketEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.ThirdpartyOrganization;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMY
 */
public class TransportWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TransportOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form TransportWorkAreaJPanel
     */
    public TransportWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            TransportOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
        populateWorkQueueTable();
    }

    public void populateWorkQueueTable() {
        DefaultTableModel model = (DefaultTableModel) transportRequestJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest work : organization.getWorkQueue().getWorkRequestList()) {
            if (work instanceof SellingWorkRequest) {
                SellingWorkRequest sellingWorkRequest = (SellingWorkRequest) work;
                Object[] row = new Object[6];
                row[0] = sellingWorkRequest;
                row[1] = sellingWorkRequest.getSource();
                row[2] = sellingWorkRequest.getDestination();
                row[3] = sellingWorkRequest.getNoOfTrucks();
                row[4] = sellingWorkRequest.getTransportationCost();
                row[5] = sellingWorkRequest.getStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        transportRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        forwardButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transportRequestJTable.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        transportRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Source", "Destination", "Trucks", "Transportation Cost", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(transportRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 780, 143));

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("WELCOME TO TRANSPORT WORKAREA ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        forwardButton.setBackground(new java.awt.Color(0, 102, 102));
        forwardButton.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        forwardButton.setForeground(new java.awt.Color(255, 255, 255));
        forwardButton.setText("FORWARD TO WHOLESALER");
        forwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardButtonActionPerformed(evt);
            }
        });
        add(forwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel2.setText("TRANSPORTATION COST* :  ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        costTextField.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(costTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void forwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = transportRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            int cost;
            boolean isValid = true;
            try {
                cost = Integer.parseInt(costTextField.getText());
            } catch (NumberFormatException e) {
                isValid = false;
                JOptionPane.showMessageDialog(null, "Enter valid cost", "Error", JOptionPane.ERROR_MESSAGE);
                throw e;
            }
            if(cost <=0){
                isValid = false;
                JOptionPane.showMessageDialog(null, "Enter valid cost", "Error", JOptionPane.ERROR_MESSAGE);
            }

            SellingWorkRequest request = (SellingWorkRequest) transportRequestJTable.getValueAt(selectedRow, 0);
            if (request.getStatus().equals("Sent To Logistics")) {
                if (isValid) {
                    request.setStatus("Forward to Wholesaler");
                    request.setTransportationCost(cost);
                    //ADD request to Market Enterprise- Transport Org
                    Organization org = null;
                    for (Network network : business.getNetworkList()) {
                        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                            if (enterprise instanceof MarketEnterprise) {
                                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                    if (organization instanceof ThirdpartyOrganization) {
                                        org = organization;
                                        break;
                                    }
                                }
                            }

                        }
                    }
                    if (org != null) {
                        org.getWorkQueue().getWorkRequestList().add(request);
                        userAccount.getWorkQueue().getWorkRequestList().add(request);
                    }
                    JOptionPane.showMessageDialog(null, "Request Forwarded to Wholesaler Sucessfully");
                     populateWorkQueueTable();
                     forwardButton.setEnabled(false);
                     costTextField.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Same Request can not be forwarded again", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_forwardButtonActionPerformed
    }
    public boolean validateCost(String cost) {

        Pattern pattern = Pattern.compile("[0-9]*");
        Matcher matcher = pattern.matcher(cost);
        if (!matcher.matches()) {

            JOptionPane.showMessageDialog(null, "Please Enter valid cost", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costTextField;
    private javax.swing.JButton forwardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable transportRequestJTable;
    // End of variables declaration//GEN-END:variables
}
