/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CarrierServiceProvider;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CarrierOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarrierWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class CarrierServiceProviderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private CarrierOrganization carrierOrganization;

    /**
     * Creates new form CarrierServiceProviderJPanel
     */
    public CarrierServiceProviderJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.carrierOrganization = (CarrierOrganization) organization;
        this.enterprise = enterprise;
        /*try{
        File dir = new File("D:\\AED\\Transfarmers\\src\\userinterface\\CarrierServiceProvider", "Images.jpeg");
        Image image=ImageIO.read(dir);
        image=image.getScaledInstance(1000, 900,java.awt.Image.SCALE_SMOOTH);
        ImageIcon picture=new ImageIcon(image);
        jLabel1.setIcon(picture);
        }
        catch(Exception e)
        {

        }*/
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCarrierRequest.getModel();

        model.setRowCount(0);

        for (WorkRequest request : carrierOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            CarrierWorkRequest carrierWorkRequest = (CarrierWorkRequest) request;
            row[0] = carrierWorkRequest;
            row[1] = carrierWorkRequest.getReceiver();
            row[2] = carrierWorkRequest.getTypeOfProvider();
            row[3] = carrierWorkRequest.getTypeOfPlan();
            row[4] = carrierWorkRequest.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarrierRequest = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        BtnProcess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCarrierRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Provider Type", "Plan Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCarrierRequest);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 660, 130));

        btnAssignToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe.setText("ASSIGN TO ME");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 140, -1));

        BtnProcess.setBackground(new java.awt.Color(0, 102, 102));
        BtnProcess.setForeground(new java.awt.Color(255, 255, 255));
        BtnProcess.setText("PROCESS");
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });
        add(BtnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 113, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("WELCOME TO CARRIER SERVICE PROVIDER WORKAREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarrierRequest.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblCarrierRequest.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } else {
                request.setReceiver(userAccount);
                request.setStatus("Pending");
                populateTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a reuest to process.");
            return;
        }

    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarrierRequest.getSelectedRow();

        if (selectedRow >= 0) {
            CarrierWorkRequest request = (CarrierWorkRequest) tblCarrierRequest.getValueAt(selectedRow, 0);
            if (request.getReceiver() == null) {
                request.setReceiver(userAccount);
            }
            request.setStatus("Completed");
            populateTable();

        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
    }//GEN-LAST:event_BtnProcessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProcess;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCarrierRequest;
    // End of variables declaration//GEN-END:variables
}
