/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicineInventory;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Organization.MedicineInventoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineSupplierWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deekshithav
 */
public class MedicineInventoryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private MedicineInventoryOrganization medicineInventoryOrganization;

    public MedicineInventoryWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.medicineInventoryOrganization = (MedicineInventoryOrganization) organization;
        this.enterprise = enterprise;
        populateTable();
    }

    /**
     * Creates new form MedicineInventoryWorkAreaJPanel
     */
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : medicineInventoryOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            MedicineSupplierWorkRequest supplierWorkRequest = (MedicineSupplierWorkRequest) request;
            row[0] = supplierWorkRequest;
            row[1] = supplierWorkRequest.getReceiver();

            if (supplierWorkRequest.getMedicine() != null) {
                row[2] = supplierWorkRequest.getMedicineName();
                //row[3] = supplierWorkRequest.getMedicine().getQuantity();
                row[3] = supplierWorkRequest.getQuantityNeeded();
            } else {
                row[2] = null;
                row[3] = null;
            }
            row[4] = request.getStatus();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTable.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Medicine", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 500, 143));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("WELCOME TO MEDICINE SUPPLIER INVENTORY WORKAREA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        acceptBtn.setBackground(new java.awt.Color(0, 102, 102));
        acceptBtn.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        acceptBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptBtn.setText("CLICK TO ACCEPT");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });
        add(acceptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row ");
            return;
        }
        boolean isValid = true;
        MedicineSupplierWorkRequest request = (MedicineSupplierWorkRequest) requestTable.getValueAt(selectedRow, 0);
        Medicine medicineRequested = request.getMedicine();
        //String name = medicineRequested.getName();
        //int qty = medicineRequested.getQuantity();
        int qty = request.getQuantityNeeded();
        String name = request.getMedicine().getName();

        for (Medicine medicine : medicineInventoryOrganization.getMedicineDirectory().getMedicineList()) {

            if (medicine.getName().equals(name)) {
                if (qty > medicine.getQuantity()) {
                    isValid = false;
                    break;
                }
            }
        }

        if (isValid) {
            request.setReceiver(userAccount);
            request.setStatus("Completed");
            // update the quantity in the inventory
            for (Medicine medicine : medicineInventoryOrganization.getMedicineDirectory().getMedicineList()) {
                if (medicine.getName().equals(name)) {
                    int q = medicine.getQuantity();
                    q = q - qty;
                    medicine.setQuantity(q);
                    break;
                }
            }
            populateTable();
            JOptionPane.showMessageDialog(null, "Required Medicines sent !!");
        } else {
            JOptionPane.showMessageDialog(null, "Not enough quantity");
        }
    }//GEN-LAST:event_acceptBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
