/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Education;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Event.Event;
import Business.Organization.MinistryOfEducationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventsWorkRequest;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AMY
 */
public class EducationEventManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private MinistryOfEducationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form EducationEventManagerWorkAreaJPanel
     */
    public EducationEventManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            MinistryOfEducationOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        venueTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        convAllowanceTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("EDUCATION MINISTRY EVENT MANAGER WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel2.setText("*EVENT NAME:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 240, -1));

        jLabel3.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel3.setText("*EVENT TYPE:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));
        add(typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 240, -1));

        jLabel5.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel5.setText("*EVENT DATE:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel6.setText("*EVENT TIME:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 240, -1));
        add(venueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 240, -1));

        jLabel7.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel7.setText("*VENUE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel4.setText("EVENT DESCRIPTION:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, 37));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 240, 72));

        jLabel8.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel8.setText("CONVEYANCE ALLOWANCE:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));
        add(convAllowanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 250, -1));

        createBtn.setBackground(new java.awt.Color(0, 102, 102));
        createBtn.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("CREATE EVENT");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel9.setText("$");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        String eventName = nameTextField.getText();
        boolean isEventNameValid = validateStrings(eventName);
        String eventType = typeTextField.getText();
         boolean iseventTypeValid = validateStrings(eventType);
        Date eventDate = jDateChooser1.getDate();
         boolean isDateValid=true;
        if(eventDate == null){
             isDateValid = false;
             JOptionPane.showMessageDialog(null, "Please Enter Date", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        if(eventDate != null && eventDate.before(new Date())){
             isDateValid = false;
             JOptionPane.showMessageDialog(null, "Please Enter Valid Date", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        String eventTime = timeTextField.getText();
        LocalTime eventTimeLocal;
        try {
            eventTimeLocal = LocalTime.parse(eventTime);
        } catch (DateTimeParseException e) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "Enter valid time in format hh:mm:ss", "Error", JOptionPane.ERROR_MESSAGE);
            throw e;
        }
        String venue = venueTextField.getText();
         boolean isEventVenueValid = validateStrings(venue);
        String desc = descriptionTextArea.getText();
        // boolean isdescValid = validateStrings(desc);

        double price;
        try {
            price = Double.parseDouble(convAllowanceTextField.getText());
        } catch (NumberFormatException e) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "Enter valid price", "Error", JOptionPane.ERROR_MESSAGE);
            throw e;
        }
        if (isValid && isEventNameValid && iseventTypeValid && isEventVenueValid && isDateValid ) {
            Event event = new Event();
            event.setEventName(eventName);
            event.setEventType(eventType);
            event.setEventDate(eventDate);
            event.setTime(eventTimeLocal);
            event.setDescription(desc);
            event.setVenue(venue);
            event.setConveyanceAllowance(price);
            EducationEventsWorkRequest educationEventsWorkRequest = new EducationEventsWorkRequest();
            educationEventsWorkRequest.setEvent(event);
            educationEventsWorkRequest.setSender(userAccount);
            educationEventsWorkRequest.setStatus("Pending");
            organization.getWorkQueue().getWorkRequestList().add(educationEventsWorkRequest);
            JOptionPane.showMessageDialog(null, "You have successfully created event!!");
            createBtn.setEnabled(false);
            
        }

    }//GEN-LAST:event_createBtnActionPerformed
   public boolean validateStrings(String name){
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter mandatory value", "Error", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        Pattern pattern = Pattern.compile("[a-zA-Z ]*");
        Matcher matcher = pattern.matcher(name);
         if (!matcher.matches()) {
             
            JOptionPane.showMessageDialog(null, "Please Enter valid string value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
      }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField convAllowanceTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextArea descriptionTextArea;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JTextField venueTextField;
    // End of variables declaration//GEN-END:variables
}
