/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;
//import org.jfree.data.category;

import org.jfree.data.category.DefaultCategoryDataset;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author jhalak
 */
public class FarmerPortalDalJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form Prediction
     */
    public FarmerPortalDalJPanel(JPanel userProcessContainer, UserAccount account,
            FarmerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnShowChart = new javax.swing.JButton();
        MoongDalPriceJPanel = new javax.swing.JPanel();
        MaizePriceTrend = new javax.swing.JPanel();
        TurDalPriceJPanel = new javax.swing.JPanel();
        btnPriceSupport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 440, 589, -1));

        btnShowChart.setBackground(new java.awt.Color(0, 102, 102));
        btnShowChart.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnShowChart.setForeground(new java.awt.Color(255, 255, 255));
        btnShowChart.setText("PRODUCTION TREND");
        btnShowChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowChartActionPerformed(evt);
            }
        });
        add(btnShowChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 40));

        MoongDalPriceJPanel.setBackground(new java.awt.Color(102, 102, 102));
        MoongDalPriceJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        MoongDalPriceJPanel.setLayout(new javax.swing.BoxLayout(MoongDalPriceJPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(MoongDalPriceJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 346, 422));

        MaizePriceTrend.setBackground(new java.awt.Color(102, 102, 102));

        TurDalPriceJPanel.setBackground(new java.awt.Color(102, 102, 102));
        TurDalPriceJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        TurDalPriceJPanel.setLayout(new javax.swing.BoxLayout(TurDalPriceJPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout MaizePriceTrendLayout = new javax.swing.GroupLayout(MaizePriceTrend);
        MaizePriceTrend.setLayout(MaizePriceTrendLayout);
        MaizePriceTrendLayout.setHorizontalGroup(
            MaizePriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(MaizePriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaizePriceTrendLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TurDalPriceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        MaizePriceTrendLayout.setVerticalGroup(
            MaizePriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(MaizePriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MaizePriceTrendLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TurDalPriceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        add(MaizePriceTrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 6, -1, 422));

        btnPriceSupport.setBackground(new java.awt.Color(0, 102, 102));
        btnPriceSupport.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnPriceSupport.setForeground(new java.awt.Color(255, 255, 255));
        btnPriceSupport.setText("MINIMUM SUPPORT PRICE TREND");
        btnPriceSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceSupportActionPerformed(evt);
            }
        });
        add(btnPriceSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, 40));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 579, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowChartActionPerformed
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(4850, "Rs/Quintiles", "2015-2016");
        dcd.setValue(5225, "Rs/Quintiles", "2016-2017");
        dcd.setValue(5700, "Rs/Quintiles", "2017-2018");

        //JFreeChart jchart=ChartFactory.createBarChart3D("Student Name", "Student Marks", TOOL_TIP_TEXT_KEY, dcd);
        JFreeChart jchart = ChartFactory.createBarChart(" Moong Dal Prices", "Years", "Prices", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.orange);

        // ChartFrame chartFrame=new ChartFrame("Student Record", jchart, true);
        //  chartFrame.setVisible(true);
        // chartFrame.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);

        MoongDalPriceJPanel.removeAll();
        MoongDalPriceJPanel.add(chartPanel);
        MoongDalPriceJPanel.updateUI();

    }//GEN-LAST:event_btnShowChartActionPerformed

    private void btnPriceSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceSupportActionPerformed
        // TODO add your handling code here:

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(4625, "Rs/Quintiles", "2015-2016");
        dcd.setValue(5050, "Rs/Quintiles", "2016-2017");
        dcd.setValue(5250, "Rs/Quintiles", "2017-2018");

        //JFreeChart jchart=ChartFactory.createBarChart3D("Student Name", "Student Marks", TOOL_TIP_TEXT_KEY, dcd);
        JFreeChart jchart = ChartFactory.createBarChart("Tur Dal Prices", "Years", "Prices", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.orange);

        // ChartFrame chartFrame=new ChartFrame("Student Record", jchart, true);
        //  chartFrame.setVisible(true);
        // chartFrame.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);

        TurDalPriceJPanel.removeAll();
        TurDalPriceJPanel.add(chartPanel);
        TurDalPriceJPanel.updateUI();

    }//GEN-LAST:event_btnPriceSupportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MaizePriceTrend;
    private javax.swing.JPanel MoongDalPriceJPanel;
    private javax.swing.JPanel TurDalPriceJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPriceSupport;
    private javax.swing.JButton btnShowChart;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
