/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;
//import org.jfree.data.category;

import org.jfree.data.category.DefaultCategoryDataset;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author jhalak
 */
public class FarmerPortalWheatJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form Prediction
     */
    public FarmerPortalWheatJPanel(JPanel userProcessContainer, UserAccount account,
            FarmerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnShowChart = new javax.swing.JButton();
        WheatProductionPanel = new javax.swing.JPanel();
        WheatPriceTrend = new javax.swing.JPanel();
        WheatPriceJPanel = new javax.swing.JPanel();
        btnPriceSupport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 444, 593, -1));

        btnShowChart.setBackground(new java.awt.Color(0, 102, 102));
        btnShowChart.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnShowChart.setForeground(new java.awt.Color(255, 255, 255));
        btnShowChart.setText("PRODUCTION TREND");
        btnShowChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowChartActionPerformed(evt);
            }
        });
        add(btnShowChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 453, -1, -1));

        WheatProductionPanel.setBackground(new java.awt.Color(102, 102, 102));
        WheatProductionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        WheatProductionPanel.setLayout(new javax.swing.BoxLayout(WheatProductionPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(WheatProductionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 346, 426));

        WheatPriceTrend.setBackground(new java.awt.Color(102, 102, 102));

        WheatPriceJPanel.setBackground(new java.awt.Color(102, 102, 102));
        WheatPriceJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        WheatPriceJPanel.setLayout(new javax.swing.BoxLayout(WheatPriceJPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout WheatPriceTrendLayout = new javax.swing.GroupLayout(WheatPriceTrend);
        WheatPriceTrend.setLayout(WheatPriceTrendLayout);
        WheatPriceTrendLayout.setHorizontalGroup(
            WheatPriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(WheatPriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WheatPriceTrendLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WheatPriceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        WheatPriceTrendLayout.setVerticalGroup(
            WheatPriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(WheatPriceTrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WheatPriceTrendLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WheatPriceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        add(WheatPriceTrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 6, -1, 426));

        btnPriceSupport.setBackground(new java.awt.Color(0, 102, 102));
        btnPriceSupport.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnPriceSupport.setForeground(new java.awt.Color(255, 255, 255));
        btnPriceSupport.setText("MINIMUM SUPPORT PRICE TREND");
        btnPriceSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceSupportActionPerformed(evt);
            }
        });
        add(btnPriceSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 450, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowChartActionPerformed
        // TODO add your handling code here:
        // DefaultCategoryDataSet dcd=new DefaultCategoryDataSet();

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(95, "Production", "FY12");
        dcd.setValue(94, "Production", "FY13");
        dcd.setValue(94, "Production", "FY14");
        dcd.setValue(96, "Production", "FY15");
        dcd.setValue(89, "Production", "FY16");
        dcd.setValue(97, "Production", "FY17");
        //JFreeChart jchart=ChartFactory.createBarChart3D("Student Name", "Student Marks", TOOL_TIP_TEXT_KEY, dcd);
        JFreeChart jchart = ChartFactory.createBarChart("Wheat Production", "Years", "Percentage", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.blue);

        // ChartFrame chartFrame=new ChartFrame("Student Record", jchart, true);
        //  chartFrame.setVisible(true);
        // chartFrame.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);

        WheatProductionPanel.removeAll();
        WheatProductionPanel.add(chartPanel);
        WheatProductionPanel.updateUI();

    }//GEN-LAST:event_btnShowChartActionPerformed

    private void btnPriceSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceSupportActionPerformed
        // TODO add your handling code here:

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(60, "Prices", "2004-2008");
        dcd.setValue(30, "Prices", "2009-2013");
        dcd.setValue(17, "Prices", "2014-2017/2018");

        //JFreeChart jchart=ChartFactory.createBarChart3D("Student Name", "Student Marks", TOOL_TIP_TEXT_KEY, dcd);
        JFreeChart jchart = ChartFactory.createBarChart("Wheat Prices", "Years", "Percentage", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.orange);

        // ChartFrame chartFrame=new ChartFrame("Student Record", jchart, true);
        //  chartFrame.setVisible(true);
        // chartFrame.setSize(500, 400);
        ChartPanel chartPanel = new ChartPanel(jchart);

        WheatPriceJPanel.removeAll();
        WheatPriceJPanel.add(chartPanel);
        WheatPriceJPanel.updateUI();

    }//GEN-LAST:event_btnPriceSupportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WheatPriceJPanel;
    private javax.swing.JPanel WheatPriceTrend;
    private javax.swing.JPanel WheatProductionPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPriceSupport;
    private javax.swing.JButton btnShowChart;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
