/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.Crops.Crop;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jhalak
 */
public class FarmerAnalysisJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;

    /**
     * Creates new form FarmerAnalysisJPanel
     */
    public FarmerAnalysisJPanel(JPanel userProcessContainer, UserAccount account,
            FarmerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
        populateComboBox();
    }

    private void populateComboBox() {
        cropJComboBox.removeAllItems();
        for (Crop.CropType crop : Crop.CropType.values()) {
            cropJComboBox.addItem(crop);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWheat = new javax.swing.JButton();
        btnCereals = new javax.swing.JButton();
        btnRice = new javax.swing.JButton();
        btnDal = new javax.swing.JButton();
        lblWheat = new javax.swing.JLabel();
        lblRice = new javax.swing.JLabel();
        lblMaize = new javax.swing.JLabel();
        lblDal = new javax.swing.JLabel();
        showSellingPricesBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ViewWorkRequestBtn = new javax.swing.JButton();
        viewCropBreakUp = new javax.swing.JButton();
        ViewCropBreakUpPanel2 = new javax.swing.JPanel();
        cropJComboBox = new javax.swing.JComboBox();
        expenditureTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCotton = new javax.swing.JButton();
        lblMaize1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWheat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/wheat.jpg"))); // NOI18N
        btnWheat.setText("jButton1");
        btnWheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWheatActionPerformed(evt);
            }
        });
        add(btnWheat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 90));

        btnCereals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/Cereal.jpeg"))); // NOI18N
        btnCereals.setText("jButton3");
        btnCereals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerealsActionPerformed(evt);
            }
        });
        add(btnCereals, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 160, 100));

        btnRice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/Rice.jpg"))); // NOI18N
        btnRice.setText("jButton1");
        btnRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiceActionPerformed(evt);
            }
        });
        add(btnRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 160, 90));

        btnDal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/Dal.jpeg"))); // NOI18N
        btnDal.setText("jButton1");
        btnDal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDalActionPerformed(evt);
            }
        });
        add(btnDal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 160, 90));

        lblWheat.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        lblWheat.setForeground(new java.awt.Color(0, 102, 102));
        lblWheat.setText("WHEAT");
        add(lblWheat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 80, 20));

        lblRice.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        lblRice.setForeground(new java.awt.Color(0, 102, 102));
        lblRice.setText("RICE");
        add(lblRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 40, 20));

        lblMaize.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        lblMaize.setForeground(new java.awt.Color(0, 102, 102));
        lblMaize.setText("COTTON");
        add(lblMaize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 80, 20));

        lblDal.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        lblDal.setForeground(new java.awt.Color(0, 102, 102));
        lblDal.setText("DAL");
        add(lblDal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 30, 20));

        showSellingPricesBtn.setBackground(new java.awt.Color(0, 102, 102));
        showSellingPricesBtn.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        showSellingPricesBtn.setForeground(new java.awt.Color(255, 255, 255));
        showSellingPricesBtn.setText("SHOW SELLING PRIZE");
        showSellingPricesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSellingPricesBtnActionPerformed(evt);
            }
        });
        add(showSellingPricesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 40));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 450, 250));

        ViewWorkRequestBtn.setBackground(new java.awt.Color(0, 102, 102));
        ViewWorkRequestBtn.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        ViewWorkRequestBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewWorkRequestBtn.setText("View Work Request Summary");
        ViewWorkRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewWorkRequestBtnActionPerformed(evt);
            }
        });
        add(ViewWorkRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 770, 600, 40));

        viewCropBreakUp.setBackground(new java.awt.Color(0, 102, 102));
        viewCropBreakUp.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        viewCropBreakUp.setForeground(new java.awt.Color(255, 255, 255));
        viewCropBreakUp.setText("VIEW CROP BREAK UP");
        viewCropBreakUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCropBreakUpActionPerformed(evt);
            }
        });
        add(viewCropBreakUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, 30));

        ViewCropBreakUpPanel2.setLayout(new javax.swing.BoxLayout(ViewCropBreakUpPanel2, javax.swing.BoxLayout.LINE_AXIS));
        add(ViewCropBreakUpPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 550, 250));

        cropJComboBox.setForeground(new java.awt.Color(0, 102, 102));
        cropJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cropJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropJComboBoxActionPerformed(evt);
            }
        });
        add(cropJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 170, 30));

        expenditureTextField.setForeground(new java.awt.Color(0, 102, 102));
        add(expenditureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 170, -1));

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("OTHER EXPENDITURE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        btnCotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/Cotton.jpg"))); // NOI18N
        btnCotton.setText("jButton1");
        btnCotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCottonActionPerformed(evt);
            }
        });
        add(btnCotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 170, 80));

        lblMaize1.setFont(new java.awt.Font("Chalkboard SE", 1, 14)); // NOI18N
        lblMaize1.setForeground(new java.awt.Color(0, 102, 102));
        lblMaize1.setText("MAIZE");
        add(lblMaize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 50, 20));

        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("CLICK THE CROP TO VIEW THE MARKET TREND");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 30, 410, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnWheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWheatActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FarmerPortalWheatJPanel", new FarmerPortalWheatJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWheatActionPerformed

    private void btnRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiceActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FarmerPortalRiceJPanel", new FarmerPortalRiceJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRiceActionPerformed

    private void btnCerealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerealsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FarmerPortalCerealJPanel", new FarmerPortalCerealJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnCerealsActionPerformed

    private void btnDalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDalActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FarmerPortalDalJPanel", new FarmerPortalDalJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDalActionPerformed

    private void showSellingPricesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSellingPricesBtnActionPerformed
        // TODO add your handling code here:

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        ArrayList<WorkRequest> list = userAccount.getWorkQueue().getWorkRequestList();
        for (WorkRequest workRequest : list) {
            if (workRequest instanceof SellingWorkRequest) {
                if (workRequest.getStatus() != null && workRequest.getStatus().equals("Completed")) {
                    int sellingPrice = ((SellingWorkRequest) workRequest).getSellingPrice();
                    String crop = ((SellingWorkRequest) workRequest).getProductName();
                    dcd.setValue(sellingPrice, "Selling Price", crop);
                }

            }
        }

        JFreeChart jchart = ChartFactory.createBarChart("Selling Summary", "Crops", "Prices", dcd, PlotOrientation.VERTICAL, true, true, true);

        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.green);
        ChartPanel chartPanel = new ChartPanel(jchart);

        jPanel1.removeAll();
        jPanel1.add(chartPanel);
        jPanel1.updateUI();

    }//GEN-LAST:event_showSellingPricesBtnActionPerformed

    private void ViewWorkRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewWorkRequestBtnActionPerformed
        // TODO add your handling code here:
        FarmerWorkAreaJPanel farmerWorkAreaJPanel1 = new FarmerWorkAreaJPanel(userProcessContainer, userAccount, (FarmerOrganization) organization, enterprise, business);
        userProcessContainer.add("farmerWorkAreaJPanel1", farmerWorkAreaJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ViewWorkRequestBtnActionPerformed

    private void cropJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropJComboBoxActionPerformed

    }//GEN-LAST:event_cropJComboBoxActionPerformed

    private void viewCropBreakUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCropBreakUpActionPerformed
        // TODO add your handling code here:
        String cropSelected = (String) cropJComboBox.getSelectedItem().toString();
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        ArrayList<WorkRequest> list = userAccount.getWorkQueue().getWorkRequestList();
        int sellingPrice = 0;
        int transportCost = 0;
        double commision = 0;
        for (WorkRequest workRequest : list) {
            if (workRequest instanceof SellingWorkRequest) {
                if (workRequest.getStatus() != null && workRequest.getStatus().equals("Completed")) {
                    String crop = ((SellingWorkRequest) workRequest).getProductName();
                    if (crop.equals(cropSelected)) {
                        sellingPrice = sellingPrice + ((SellingWorkRequest) workRequest).getSellingPrice();
                        transportCost = transportCost + ((SellingWorkRequest) workRequest).getTransportationCost();
                        commision = commision + ((SellingWorkRequest) workRequest).getCommission();

                    }

                }

            }
        }
        String expCost = expenditureTextField.getText();
        int q;
        try {
            q = Integer.parseInt(expCost);
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Enter valid cost", "Error", JOptionPane.ERROR_MESSAGE);
            throw e;
        }
        boolean isValid=true;
        if(q<= 0 ){
             isValid = false;
           JOptionPane.showMessageDialog(null, "Enter valid cost", "Error", JOptionPane.ERROR_MESSAGE);
           
        }
        if(isValid){
        double netProfit = sellingPrice - (transportCost + commision + q);
        dcd.setValue(sellingPrice, "Cost Break Up", "Selling Price");
        dcd.setValue(transportCost, "Cost Break Up", "Transportation cost");
        dcd.setValue(commision, "Cost Break Up", "Wholesaler Commission");
        dcd.setValue(q, "Cost Break Up", "Additional Costs");
        dcd.setValue(netProfit, "Cost Break Up", "Net Profit/ Loss");

        JFreeChart jchart = ChartFactory.createBarChart("Cost Break Up Summary", cropSelected + " Crop", "Prices", dcd, PlotOrientation.VERTICAL, true, true, true);

        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.green);
        ChartPanel chartPanel = new ChartPanel(jchart);

        ViewCropBreakUpPanel2.removeAll();
        ViewCropBreakUpPanel2.add(chartPanel);
        ViewCropBreakUpPanel2.updateUI();
        }
       

    }//GEN-LAST:event_viewCropBreakUpActionPerformed

    private void btnCottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCottonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FarmerPortalCottonJPanel", new FarmerPortalCottonJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCottonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewCropBreakUpPanel2;
    private javax.swing.JButton ViewWorkRequestBtn;
    private javax.swing.JButton btnCereals;
    private javax.swing.JButton btnCotton;
    private javax.swing.JButton btnDal;
    private javax.swing.JButton btnRice;
    private javax.swing.JButton btnWheat;
    private javax.swing.JComboBox cropJComboBox;
    private javax.swing.JTextField expenditureTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDal;
    private javax.swing.JLabel lblMaize;
    private javax.swing.JLabel lblMaize1;
    private javax.swing.JLabel lblRice;
    private javax.swing.JLabel lblWheat;
    private javax.swing.JButton showSellingPricesBtn;
    private javax.swing.JButton viewCropBreakUp;
    // End of variables declaration//GEN-END:variables
}
