/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.Crops.Crop;
import Business.Crops.Crop.CropType;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LogisticsEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AMY
 */
public class RequestSellingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form RequestSellingJPanel
     */
    public RequestSellingJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        populateComboBox();
    }
    private void populateComboBox() {
        cropJComboBox.removeAllItems();
        for (CropType crop : CropType.values()) {
            cropJComboBox.addItem(crop);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        noOfTrucksTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        cropJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel1.setText("1. SOURCE : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel2.setText("2. DESTINATION:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel3.setText("3. NUMBER OF TRUCKS REQUIRED : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel4.setText("4. PRODUCT NAME :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        add(sourceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 190, 30));
        add(destinationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 190, 30));

        noOfTrucksTextField.setEnabled(false);
        add(noOfTrucksTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 30));

        createBtn.setBackground(new java.awt.Color(0, 102, 102));
        createBtn.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("SUBMIT");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 190, -1));

        jLabel5.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("SELLING PRODUCT PORTAL");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        jLabel6.setText("5. QUANTITY: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 190, 30));

        cropJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cropJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropJComboBoxActionPerformed(evt);
            }
        });
        add(cropJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setText("(500-5000 Lbs) ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        String source = sourceTextField.getText();
        boolean issourceValid = validateStrings(source);
        String destination = destinationTextField.getText();
        boolean isdestinationValid = validateStrings(destination);
       // String noOfTrucks = noOfTrucksTextField.getText();
       
        
//        try {
//            trucks = Integer.parseInt(noOfTrucks);
//        } catch (NumberFormatException e) {
//            isValid = false;
//            JOptionPane.showMessageDialog(null, "Enter valid number of trucks", "Error", JOptionPane.ERROR_MESSAGE);
//            throw e;
//        }
        String productName = (String)cropJComboBox.getSelectedItem().toString();
        boolean isproductNameValid = validateStrings(productName);
        String qty = quantityTextField.getText();      
        int q;
         try {
            q =  Integer.parseInt(qty);
        } catch (NumberFormatException e) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "Enter valid Quantity", "Error", JOptionPane.ERROR_MESSAGE);
            throw e;
        }
         if(q == 0 || q < 500){
            isValid = false;
            JOptionPane.showMessageDialog(null, "Enter valid Quantity Between 500 and 5000 lbs", "Error", JOptionPane.ERROR_MESSAGE);

         }
         int trucks=0;
        if (isValid) {
            if (q >= 500 && q <= 1000) {
                trucks = 1;
            } else if (q > 1000 && q <= 2000) {
                trucks = 2;
            } else if (q > 2000 && q <= 3000) {
                trucks = 3;
            } else if (q > 3000 && q <= 4000) {
                trucks = 4;
            } else if (q > 4000 && q <= 5000) {
                trucks = 5;
            }
            noOfTrucksTextField.setText(String.valueOf(trucks));
        }
        if(isValid && issourceValid && isdestinationValid && isproductNameValid) {
        SellingWorkRequest sellingWorkRequest = new SellingWorkRequest();
        sellingWorkRequest.setSource(source);
        sellingWorkRequest.setDestination(destination);
        sellingWorkRequest.setNoOfTrucks(trucks);
        sellingWorkRequest.setProductName(productName);
        sellingWorkRequest.setQuantity(q);
        sellingWorkRequest.setSender(userAccount);
        sellingWorkRequest.setStatus("Sent To Logistics");

        Organization org = null;
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof LogisticsEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof TransportOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }

            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(sellingWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(sellingWorkRequest);
        }
        JOptionPane.showMessageDialog(null, "Request Created Sucessfully");
        createBtn.setEnabled(false);
        sourceTextField.setText("");
        destinationTextField.setText("");
        quantityTextField.setText("");
        noOfTrucksTextField.setText("");
        cropJComboBox.removeAllItems();
        }
    }//GEN-LAST:event_createBtnActionPerformed
 public boolean validateStrings(String name){
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter mandatory value", "Error", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        Pattern pattern = Pattern.compile("[a-zA-Z ]*");
        Matcher matcher = pattern.matcher(name);
         if (!matcher.matches()) {
             
            JOptionPane.showMessageDialog(null, "Please Enter valid string value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
      }
        return true;
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FarmerWorkAreaJPanel dwjp = (FarmerWorkAreaJPanel) component;
        dwjp.populateSellingRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void cropJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropJComboBoxActionPerformed
      
    }//GEN-LAST:event_cropJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox cropJComboBox;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField noOfTrucksTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField sourceTextField;
    // End of variables declaration//GEN-END:variables
}
