/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BankingFinance;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BankingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InterestFreeLoanWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class BankingFinanceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private BankingOrganization bankingOrganization;

    /**
     * Creates new form BankingFinanceJPanel
     */
    public BankingFinanceJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.bankingOrganization = (BankingOrganization) organization;
        this.enterprise = enterprise;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblInterestFreeLoanRequest.getModel();

        model.setRowCount(0);

        for (WorkRequest request : bankingOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[7];
            InterestFreeLoanWorkRequest interestFreeLoanWorkRequest = (InterestFreeLoanWorkRequest) request;
            row[0] = interestFreeLoanWorkRequest;
            row[1] = interestFreeLoanWorkRequest.getReceiver();
            row[2] = interestFreeLoanWorkRequest.getMonthlyIncome();
            row[3] = interestFreeLoanWorkRequest.IsAgriLand();
            row[4] = interestFreeLoanWorkRequest.IsCurrentIncome();
            row[5] = interestFreeLoanWorkRequest.IsLoanUsed();
            row[6] = interestFreeLoanWorkRequest.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblInterestFreeLoanRequest = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        BtnProcess = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        imageDisplayLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInterestFreeLoanRequest.setFont(new java.awt.Font("Chalkboard SE", 1, 12)); // NOI18N
        tblInterestFreeLoanRequest.setForeground(new java.awt.Color(0, 0, 153));
        tblInterestFreeLoanRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Monthly Income", "Agricultural Land proof", "Current Income Proof", "Loan Usage Proof", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInterestFreeLoanRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInterestFreeLoanRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInterestFreeLoanRequest);
        if (tblInterestFreeLoanRequest.getColumnModel().getColumnCount() > 0) {
            tblInterestFreeLoanRequest.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblInterestFreeLoanRequest.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblInterestFreeLoanRequest.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 790, 120));

        btnAssignToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToMe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 113, -1));

        BtnProcess.setBackground(new java.awt.Color(0, 102, 102));
        BtnProcess.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnProcess.setForeground(new java.awt.Color(255, 255, 255));
        BtnProcess.setText("Process >>");
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });
        add(BtnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 113, -1));

        lblBanner.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(0, 102, 102));
        lblBanner.setText("FARM LOAN");
        add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, 20));

        lblName.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        lblName.setText("1. NAME :");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        lblAge.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        lblAge.setText("2. AGE:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        lblGender.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        lblGender.setText("3. GENDER:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        lblAddress.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        lblAddress.setText("4. ADDRESS:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        txtName.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 170, -1));

        txtAge.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 170, -1));

        txtGender.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 170, -1));

        txtAddress.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 170, -1));

        imageDisplayLabel.setText("Label");
        add(imageDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 250, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInterestFreeLoanRequest.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblInterestFreeLoanRequest.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Completed")
                    || request.getStatus().equalsIgnoreCase("Request Processed and Loan Approved")
                    || request.getStatus().equalsIgnoreCase("Loan Not Approved")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } else {
                request.setReceiver(userAccount);
                request.setStatus("Pending");
                populateTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
            return;
        }

    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInterestFreeLoanRequest.getSelectedRow();

        if (selectedRow >= 0) {
            InterestFreeLoanWorkRequest request = (InterestFreeLoanWorkRequest) tblInterestFreeLoanRequest.getValueAt(selectedRow, 0);
            if (request.getReceiver() == null) {
                request.setReceiver(userAccount);
            }
            //Above 200, Between 100 and 300, Below 100
            if ((request.IsAgriLand() || request.IsCurrentIncome() || request.IsLoanUsed())
                    && request.getMonthlyIncome().equals("Below 10000")) {
                request.setStatus("Request Processed and Loan Approved");
            } else {
                request.setStatus("Loan Not Approved");
            }

            populateTable();

        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
    }//GEN-LAST:event_BtnProcessActionPerformed

    private void tblInterestFreeLoanRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInterestFreeLoanRequestMouseClicked
        // TODO add your handling code here:
                  int selectedRow = tblInterestFreeLoanRequest.getSelectedRow();

        if (selectedRow >= 0) {
            InterestFreeLoanWorkRequest request = (InterestFreeLoanWorkRequest) tblInterestFreeLoanRequest.getValueAt(selectedRow, 0);
            
        txtName.setText(request.getName());
        txtAddress.setText(request.getAddress());
        txtAge.setText(String.valueOf(request.getAge()));
        txtGender.setText(request.getGender());
        imageDisplayLabel.setIcon(request.getImage());
        }
    }//GEN-LAST:event_tblInterestFreeLoanRequestMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProcess;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JLabel imageDisplayLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblInterestFreeLoanRequest;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
